services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      INIT_MEMORY: 4G
      MAX_MEMORY: 8G
      SERVER_NAME: "The Joe Server"
      ICON: "https://cdn.discordapp.com/icons/693216188599238678/25b710db6fad4c4415f0d3f55b8e288f.png?size=160&quality=lossless"
    volumes:
      - /data/minecraft_vanilla_data:/data